# Generated by Django 2.2.7 on 2019-11-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalId', models.IntegerField(default=0)),
                ('name', models.TextField()),
                ('admArea', models.TextField()),
                ('district', models.TextField()),
                ('adress', models.TextField()),
                ('deparmentalAffilation', models.TextField()),
                ('capacity', models.IntegerField(default=0)),
                ('objectOperOrgName', models.TextField()),
                ('coordinates', models.TextField()),
            ],
        ),
    ]
