# Generated by Django 2.2.7 on 2019-11-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20191123_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalId', models.IntegerField(default=0)),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('coordinates', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='coveredSlots',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='cameras',
            field=models.IntegerField(default=0),
        ),
    ]
