# Generated by Django 2.2.7 on 2019-11-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20191123_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='slotIsVisible',
        ),
        migrations.AlterField(
            model_name='camera',
            name='coveredSlots',
            field=models.TextField(blank=True),
        ),
    ]
