# Generated by Django 2.2.7 on 2019-11-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20191123_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalId', models.IntegerField(default=0)),
                ('name', models.TextField()),
                ('admArea', models.TextField()),
                ('district', models.TextField()),
                ('address', models.TextField()),
                ('objectType', models.TextField()),
                ('nameOfBusinessEntity', models.TextField()),
                ('coordinates', models.TextField()),
            ],
        ),
    ]
