# Generated by Django 2.2.7 on 2019-11-24 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_kiosk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalId', models.IntegerField(default=0)),
                ('numberOfRates', models.IntegerField(default=0)),
                ('currentRating', models.FloatField(default=3.0)),
            ],
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='userRating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.Rating'),
        ),
    ]
