# Generated by Django 2.2.7 on 2019-11-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20191124_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingslot',
            name='userRating',
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='currentRating',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='numberOfRates',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
