# Generated by Django 2.2.7 on 2019-11-23 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
    ]
